[manager] 
prepend_keymap = [
 { on = "!", run  = 'shell "pwsh.exe -noprofile -nologo -noexit -command ""function qq{exit}"" " --block', desc = "Open PowerShell here (no profile)"},
 { on = "@", run  = 'shell "pwsh.exe -nologo " --block', desc = "Open PowerShell here"},

 { on = "l", run  = 'plugin smart-enter', desc = "Enter the child directory, or open the file"},
 { on = "<Right>", run  = 'plugin smart-enter', desc = "Enter the child directory, or open the file"},

 { on = "<Home>", run  = 'arrow top', desc = "Go to top"},
 { on = "<End>", run  = 'arrow bot', desc = "Go to bottom"},
 
 { on = ["g","g"], run  = 'noop', desc = "Go to top"},
 { on = "G", run  = 'noop', desc = "Go to bottom"},
 
 { on = "<S-Home>", run  = 'seek -10000', desc = "Seek up 10000 unit in the preview"},
 { on = "<S-End>", run  = 'seek 10000', desc = "Seek down 10000 unit in the preview"},
 { on = "<S-Up>", run  = 'seek -5', desc = "Seek up 5 units in the preview"},
 { on = "<S-Down>", run  = 'seek 5', desc = "Seek down 5 units in the preview"},
 
 { on =  [ "g", "a" ], for="windows", run  = 'cd %APPDATA%', desc = "Go to AppData (Roaming)"},
 { on =  [ "g", "w" ], for="windows", run  = 'cd %WORK%', desc = "Go to %Work%"},
 { on =  [ "g", "p" ], for="windows", run  = 'cd %PROGRAMFILES%', desc = "Go to Program Files"},
 { on =  [ "g", "c" ], for="windows", run  = 'cd %APPDATA%/yazi/config', desc = "Go to Yazi config"},
 
 { on =  [ "m", "c" ], run  = 'linemode combo', desc = "Linemode: Combo"},
]
