# "$schema" = "https://yazi-rs.github.io/schemas/yazi.json"
[mgr]
show_hidden = true
ratio = [1,4,4]
show_symlink = true
linemode = "combo"

[preview]
tab_size = 2
image_filter = "triangle"
image_delay = 0
max_width = 1300
max_height = 1300
image_quality = 75

[opener]
npp = [
	{ run ='"C:\Program Files\Notepad++\notepad++.exe" %s', orphan = true, for = 'windows', desc = "Notepad++"}
]

nvim = [
	{ run = '"nvim" %s', block = true, for = 'windows', desc = 'nvim'}
]

7zip = [
	{ run = "7zFM.exe %s", orphan = true, for = 'windows', desc = 'Open in 7zip'}
]

[open]
prepend_rules = [
	{ mime = 'inode/directory', use = ["open","code","nvim"]},
	{ mime = 'inode/empty', use = ["nvim","npp"]},
	{ mime = 'text/*', use = ["nvim","npp","code"]},
	{ mime = '*/htm*', use = ["open","nvim","reveal"]},
	{ url = '*.{ini,lua}', use = ["nvim","npp","code"]},
	{ url = "*.{zip,rar,7z,tar,tgz,txz,tbz2,tzst,gz,xz,zst,bz2,cab,iso,cpio,arj,lzma}", use = [ "7zip", "extract", "reveal" ] },
	{ url = "*.tar.*", use = [ "7zip", "extract", "reveal" ] },
	{ mime = "application/{zip,rar,7z,tar,gzip,xz,zstd,bzip2,lzma,cpio,arj,iso9660,vnd.ms-cab-compressed}", use = [ "7zip", "extract", "reveal" ] },
]
append_rules = [
]

[plugin]
prepend_previewers= [
	{ url = "*.csv", run = "rich-preview"}, # for csv files
	{ url = "*.rst", run = "rich-preview"}, # for restructured text (.rst) files
	{ url = "*.ipynb", run = "rich-preview"}, # for jupyter notebooks (.ipynb)
	{ url = "*.json", run = "rich-preview"}, # for json (.json) files
	{ url = "*.ini", run='preview'},
	{ url = "*.xml", run = "code"}, # force text preview, not hexyl
	{ url = "*.{avproj,avlib,avcode,avhmi,avtype}", run = "code"}, # AVS files are XML, no <?xml prolog so mime=text/plain
	{ url = "*.{zip,rar,7z,tar,tgz,txz,tbz2,tzst,gz,xz,zst,bz2,cab,iso,cpio,arj,lzma}", run = "archive"},
	{ url = "*.tar.*", run = "archive"},
	{ mime = "application/{zip,rar,7z,tar,gzip,xz,zstd,bzip2,lzma,cpio,arj,iso9660,vnd.ms-cab-compressed}", run = "archive"},
	{ mime = "{audio,video,image}/*", run = "mediainfo"},
    { mime = "application/subrip", run = "mediainfo" },
    { mime = "application/postscript", run = "mediainfo" },
	{ url = "*.md", run = 'mdcat'},
	
]
append_previewers= [
	{ url = "*", run = 'hexyl'}
]

prepend_preloaders = [
	{ mime = "{audio,video,image}/*", run = "mediainfo" },
	{ mime = "application/subrip", run = "mediainfo" },
	{ mime = "application/postscript", run = "mediainfo" },
]

prepend_fetchers=[
	{ group = "git", url = "*", run = "git" },
	{ group = "git", url = "*/", run = "git" },
]
